package view;


import control.ControlEditora;
import control.ControlLivro;
import javax.swing.JOptionPane;
import model.Editora;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tillm
 */
public class FCadLivro extends javax.swing.JDialog {

    /**
     * Creates new form FCadLivro
     */
    public FCadLivro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencherEditoras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        edTitulo = new javax.swing.JTextField();
        edPaginas = new javax.swing.JTextField();
        edAutores = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btGravar = new javax.swing.JButton();
        ccEditora = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textTitulo.setText("Título");

        jLabel1.setText("Páginas");

        edTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edTituloActionPerformed(evt);
            }
        });

        edAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edAutoresActionPerformed(evt);
            }
        });

        jLabel2.setText("Autores");

        jLabel3.setText("Editora");

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        ccEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccEditoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(textTitulo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(edAutores, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(edTitulo)
                        .addComponent(edPaginas))
                    .addComponent(ccEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGravar)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTitulo)
                    .addComponent(edTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ccEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btGravar)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edTituloActionPerformed

    private void edAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edAutoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edAutoresActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        if(controlLivro.gravar(edTitulo.getText(), Integer.parseInt(edPaginas.getText()), edAutores.getText(), (Editora) ccEditora.getSelectedItem())){
            JOptionPane.showMessageDialog(this, "Cadastro com sucesso");
            limparCampos();
        }else{
            JOptionPane.showMessageDialog(this, "Erro");
        }
    }//GEN-LAST:event_btGravarActionPerformed

    public void limparCampos(){
        edTitulo.setText("");
        edPaginas.setText("");
        edAutores.setText("");
    }
    
    private void ccEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccEditoraActionPerformed

    /**
     * @param args the command line arguments
     */
    private void preencherEditoras(){
        for(Editora e: controlEditora.getEditoras()){
            ccEditora.addItem(e);
        }
    }

    private ControlEditora controlEditora = ControlEditora.getInstancia();
    private ControlLivro controlLivro = ControlLivro.getInstancia();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGravar;
    private javax.swing.JComboBox ccEditora;
    private javax.swing.JTextField edAutores;
    private javax.swing.JTextField edPaginas;
    private javax.swing.JTextField edTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel textTitulo;
    // End of variables declaration//GEN-END:variables
}
