package view;

import control.ControlAluno;
import control.ControlEmprestimo;
import control.ControlLivro;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Editora;
import model.Emprestimo;
import model.Livro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tillm
 */
public class FCadEmprestimo extends javax.swing.JDialog {

    /**
     * Creates new form FCadEmprestimo
     */
    public FCadEmprestimo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencherAlunos();
        preencherLivros();
    }

    public void carregarCampos(Emprestimo e) throws ParseException {
        SimpleDateFormat in = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat out = new SimpleDateFormat("dd/MM/yyyy");
        String data = out.format(in.parse(e.getData().toString()));
        edData.setText(data);
        ccAluno.setSelectedItem((Emprestimo) e);
        ccLivro.setSelectedItem((Emprestimo) e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ccAluno = new javax.swing.JComboBox();
        ccLivro = new javax.swing.JComboBox();
        edData = new javax.swing.JTextField();
        btGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Livro");

        jLabel2.setText("Aluno");

        jLabel3.setText("Data");

        ccAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccAlunoActionPerformed(evt);
            }
        });

        ccLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccLivroActionPerformed(evt);
            }
        });

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(74, 74, 74)
                        .addComponent(ccAluno, 0, 153, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ccLivro, 0, 153, Short.MAX_VALUE)
                            .addComponent(edData))))
                .addGap(128, 128, 128))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGravar)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(edData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ccLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ccAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btGravar)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ccLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccLivroActionPerformed

    }//GEN-LAST:event_ccLivroActionPerformed

    private void ccAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccAlunoActionPerformed

    }//GEN-LAST:event_ccAlunoActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        try {
            if (controlEmprestimo.gravar(edData.getText(), (Livro) ccLivro.getSelectedItem(), (Aluno) ccAluno.getSelectedItem())) {
                JOptionPane.showMessageDialog(this, "Cadastro com sucesso");
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro");
            }
        } catch (ParseException ex) {
            Logger.getLogger(FCadEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btGravarActionPerformed

    public void limparCampos() {
        edData.setText("");
    }

    /**
     * @param args the command line arguments
     */
    private void preencherAlunos() {
        for (Aluno a : controlAluno.getAlunos()) {
            ccAluno.addItem(a);
        }
    }

    private void preencherLivros() {
        for (Livro l : controlLivro.getLivros()) {
            ccLivro.addItem(l);
        }
    }

    private ControlLivro controlLivro = ControlLivro.getInstancia();
    private ControlAluno controlAluno = ControlAluno.getInstancia();
    private ControlEmprestimo controlEmprestimo = ControlEmprestimo.getInstancia();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGravar;
    private javax.swing.JComboBox ccAluno;
    private javax.swing.JComboBox ccLivro;
    private javax.swing.JTextField edData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
