/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControlEmprestimo;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Emprestimo;

/**
 *
 * @author tillm
 */
public class FConsEmprestimo extends javax.swing.JDialog {

    /**
     * Creates new form FConsEmprestimo
     */
    public FConsEmprestimo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarEmprestimos();
    }

    public void carregarEmprestimos(){
        for(Emprestimo e: controlEmprestimo.getEmprestimos()){
            if(!e.isDevolvido()){
                modelEmprestimo.adicionarEmprestimo(e);
            }           
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmprestimos = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btDevolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbEmprestimos.setModel(modelEmprestimo);
        jScrollPane1.setViewportView(tbEmprestimos);

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btDevolver.setText("Devolver");
        btDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btDevolver))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar)
                    .addComponent(btExcluir)
                    .addComponent(btDevolver))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int linha = tbEmprestimos.getSelectedRow();
        if(linha >=0){
            if(controlEmprestimo.excluir(modelEmprestimo.getEmprestimo(linha))){
                modelEmprestimo.removerEmprestimo(linha);
                JOptionPane.showMessageDialog(this, "Excluido com sucesso");
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao excluir");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione um registro");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDevolverActionPerformed
        int linha = tbEmprestimos.getSelectedRow();
        if(linha >=0){
            if(controlEmprestimo.devolver(modelEmprestimo.getEmprestimo(linha))){
                modelEmprestimo.atualizarEmprestimo(linha);
                JOptionPane.showMessageDialog(this, "Devolvido com sucesso");
            }else{
                JOptionPane.showMessageDialog(this, "Erro");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione um registro");
        }
    }//GEN-LAST:event_btDevolverActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        int linha = tbEmprestimos.getSelectedRow();
        if(linha >=0){
            Emprestimo e = modelEmprestimo.getEmprestimo(linha);
            controlEmprestimo.setEmprestimo(e);
            FCadEmprestimo telaEmprestimo = new FCadEmprestimo(null, true);
            try {
                telaEmprestimo.carregarCampos(e);
            } catch (ParseException ex) {
                Logger.getLogger(FConsEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
            }
            telaEmprestimo.setVisible(true);
            modelEmprestimo.atualizar(linha);
        }else{
            JOptionPane.showMessageDialog(this, "Selecione um registro");
        }
    }//GEN-LAST:event_btEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    ModelEmprestimo modelEmprestimo = new ModelEmprestimo();
    ControlEmprestimo controlEmprestimo = new ControlEmprestimo();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDevolver;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEmprestimos;
    // End of variables declaration//GEN-END:variables
}
