package view;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tillm
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnEditora = new javax.swing.JMenuItem();
        mnAluno = new javax.swing.JMenuItem();
        btLivro = new javax.swing.JMenuItem();
        btEmprestimo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btEditoras = new javax.swing.JMenuItem();
        btLivros = new javax.swing.JMenuItem();
        btEmprestimos = new javax.swing.JMenuItem();
        btAlunos = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastros");

        mnEditora.setText("Editora");
        mnEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditoraActionPerformed(evt);
            }
        });
        jMenu1.add(mnEditora);

        mnAluno.setText("Aluno");
        mnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(mnAluno);

        btLivro.setText("Livro");
        btLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLivroActionPerformed(evt);
            }
        });
        jMenu1.add(btLivro);

        btEmprestimo.setText("Emprestimo");
        btEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmprestimoActionPerformed(evt);
            }
        });
        jMenu1.add(btEmprestimo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        btEditoras.setText("Editoras");
        btEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditorasActionPerformed(evt);
            }
        });
        jMenu2.add(btEditoras);

        btLivros.setText("Livros");
        btLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLivrosActionPerformed(evt);
            }
        });
        jMenu2.add(btLivros);

        btEmprestimos.setText("Emprestimos");
        btEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmprestimosActionPerformed(evt);
            }
        });
        jMenu2.add(btEmprestimos);

        btAlunos.setText("Alunos");
        btAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlunosActionPerformed(evt);
            }
        });
        jMenu2.add(btAlunos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditoraActionPerformed
        FCadCadastro telaEditora = new FCadCadastro(this, true);
        telaEditora.setVisible(true);
    }//GEN-LAST:event_mnEditoraActionPerformed

    private void mnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlunoActionPerformed
        FCadAluno telaAluno = new FCadAluno(this, true);
        telaAluno.setVisible(true);
    }//GEN-LAST:event_mnAlunoActionPerformed

    private void btLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLivroActionPerformed
        FCadLivro telaLivro = new FCadLivro(this, true);
        telaLivro.setVisible(true);
    }//GEN-LAST:event_btLivroActionPerformed

    private void btEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmprestimoActionPerformed
        FCadEmprestimo telaEmprestimo = new FCadEmprestimo(this, true);
        telaEmprestimo.setVisible(true);
    }//GEN-LAST:event_btEmprestimoActionPerformed

    private void btEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditorasActionPerformed
        FConsEditora telaConsEditora = new FConsEditora(this, true);
        telaConsEditora.setVisible(true);
    }//GEN-LAST:event_btEditorasActionPerformed

    private void btAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlunosActionPerformed
        FConsAluno telaConsAluno = new FConsAluno(this, true);
        telaConsAluno.setVisible(true);
    }//GEN-LAST:event_btAlunosActionPerformed

    private void btLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLivrosActionPerformed
        FConsLivro telaConsLivro = new FConsLivro(this, true);
        telaConsLivro.setVisible(true);
    }//GEN-LAST:event_btLivrosActionPerformed

    private void btEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmprestimosActionPerformed
        FConsEmprestimo telaConsEmprestimo = new FConsEmprestimo(this, true);
        telaConsEmprestimo.setVisible(true);
    }//GEN-LAST:event_btEmprestimosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btAlunos;
    private javax.swing.JMenuItem btEditoras;
    private javax.swing.JMenuItem btEmprestimo;
    private javax.swing.JMenuItem btEmprestimos;
    private javax.swing.JMenuItem btLivro;
    private javax.swing.JMenuItem btLivros;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnAluno;
    private javax.swing.JMenuItem mnEditora;
    // End of variables declaration//GEN-END:variables
}
